### ISSUE TITLE
Examples won't compile with GCC 15.1

### ISSUE THREAD

**Issue by ABelliqueux** [ABelliqueux/nolibgs_hello_worlds#6]
I suspect mipsel GCC 15.1 breaks something, because I am getting an error about "FntPrint()"  when trying to use that.

I have yet to confirm this, but for those encountering an issue, reverting to mipsel GCC 14.3  fixed it.

Maybe re-creating the .a files in `/psyq/lib` according to https://github.com/pcsx-redux/nugget/tree/main/psyq#converting-all-the-files would fix the issue ?

Example of error message:
```
hello_cdda.c: In function 'main':
hello_cdda.c:88:9: error: too many arguments to function 'FntPrint'; expected 0, have 1
   88 |         FntPrint("No TOC found: please use CD-DA disc...\n");
      |         ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from hello_cdda.c:8:
/home/arthus/build/psxdev/nolibgs_hello_worlds/psyq-4.7-converted-full/include/libgpu.h:713:12: note: declared here
  713 | extern int FntPrint();
      |            ^~~~~~~~
hello_cdda.c:123:9: error: too many arguments to function 'FntPrint'; expected 0, have 1
  123 |         FntPrint("Hello CDDA !\n");  // Send string to print stream
      |         ^~~~~~~~ ~~~~~~~~~~~~~~~~
/home/arthus/build/psxdev/nolibgs_hello_worlds/psyq-4.7-converted-full/include/libgpu.h:713:12: note: declared here
  713 | extern int FntPrint();
      |            ^~~~~~~~
hello_cdda.c:124:9: error: too many arguments to function 'FntPrint'; expected 0, have 2
  124 |         FntPrint("Playback status: %d", result[1]);  // Send string to print stream
      |         ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
/home/arthus/build/psxdev/nolibgs_hello_worlds/psyq-4.7-converted-full/include/libgpu.h:713:12: note: declared here
  713 | extern int FntPrint();
      |            ^~~~~~~~
make: *** [<commande interne>: hello_cdda.o] Error 1

```

**Comment by neoNuxxy** [comment]
Hello, I think this could fix the problem, hit me up if I'm correct idk what the output should be, but it shows something...
I just started learning how to develop for the psx, today... so I might be incorrect xD

**_Error:_**
`/home/nuxxyy/nolibgs_hello_worlds/psyq/include/libgpu.h:713:13: note: declared here
  713 | extern void FntPrint();`

**_Solution:_**

1.  Go to `./nolibgs_hello_worlds/psyq/include/libgpu.h`
2.  Copy this in line 713 `extern void FntPrint(...);`

Yes, I comfirm it works with the latest gcc version as today (15) on Arch Linux
